version: '3.8'
services:
  hexcub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      VITE_API_URI: "https://hexcubapi.zqdevs.my.id"
      VITE_BASE_URL: "https://hexcub.zqdevs.my.id"
      VITE_GEMINI_API_KEY: "AIzaSyCiObDSuGSrZOFlEP60tT6wiw_FTzsQct8"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email afn.happy@gmail.com -d hexcub.zqdevs.my.id --agree-tos
